title: Cookies and Web Activity Collection
description: A deep look at cookies (no, the other kind of cookies), how Internet activity is collected and tracked, and how cookies serve to modify the experience of the user
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
